FROM golang:1.21.0

WORKDIR /app
COPY . .

ARG ZINCSEARCH_URL
ARG ZINCSEARCH_USER
ARG ZINCSEARCH_PASSWORD

ENV ZINCSEARCH_URL=$ZINCSEARCH_URL
ENV ZINCSEARCH_USER=$ZINCSEARCH_USER
ENV ZINCSEARCH_PASSWORD=$ZINCSEARCH_PASSWORD

# Build
RUN CGO_ENABLED=0 GOOS=linux go build -o /build/app -buildvcs=false

EXPOSE 3000

# Run
CMD ["/build/app"]